### ISSUE TITLE
.

### ISSUE THREAD

**Issue by raxl8** [Hazbelll/HB-PlayerController#3]

**Comment by Hazbelll** [comment]
![Reproduction Image](https://cdn.discordapp.com/attachments/193035695722463233/411626120744665088/unknown.png)

Fine for me, I can't reproduce your issue. By the looks of that stack trace, your issue is to do with On-Screen Notifications erroring when drawn. It's not to do with this Addon, we don't draw custom/overridden notifications.

**Comment by DarkShoz** [comment]
It’s not when i load the addon it’s when i control someone and i spawn a prop that gives me infinite loop of this error.

**Comment by Hazbelll** [comment]
Please read my previous post.

**Comment by DarkShoz** [comment]
Does ‘Modern Notification’ cause this pronlem ?

**Comment by Hazbelll** [comment]
Possibly. I don't know. You'd have to solve that yourself.

**Comment by DarkShoz** [comment]
Ok thanks you for your help !
